import { ThemeProvider } from '@dariotriedcoding/next-themify'
import { Keys } from '@dariotriedcoding/next-themify/types'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const keys = {theme: ['custom-1', 'custom-2']} as const satisfies Keys

  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemeProvider<typeof keys>
          config={{
            mode: {
              strategy: 'light_dark',
              enableSystem: true,
              preferred: 'system',
              fallback: 'light',
              keys: {
                light: 'light',
                dark: 'dark',
                system: 'system',
              },
            },
            theme: {
              strategy: 'multi',
              keys: ['custom-1', 'custom-2'],
              preferred: 'custom-2'
            },
          }}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
