import { ThemeProvider } from '@dariotriedcoding/next-themify'
import { Keys } from '@dariotriedcoding/next-themify/types'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const keys = {
    mode: ['pumpkin', 'monospace']
  } as const satisfies Keys

  return (
    <html lang='en'>
      <body>
        <ThemeProvider<typeof keys>
          config={{
            mode: {
              strategy: 'custom',
              keys: ['pumpkin', 'monospace'],
              default: 'pumpkin',
            },
          }}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
