import { ThemeProvider } from '@dariotriedcoding/next-themify'
import { Keys } from '@dariotriedcoding/next-themify/types'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const keys = {
    mode: {
      custom: ['prova1', 'prova2'],
    },
  } as const satisfies Keys

  return (
    <html lang='en'>
      <body>
        <ThemeProvider<typeof keys>
          config={{
            mode: {
              strategy: 'light_dark',
              enableSystem: false,
              keys: {
                light: 'light',
                dark: 'dark',
                custom: [
                  { key: 'prova1', colorScheme: 'dark' },
                  { key: 'prova2', colorScheme: 'light' },
                ],
              },
              default: 'light',
            },
            theme: {
              strategy: 'mono',
              key: 'default',
            },
          }}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
